[package]
name = "use_myinotify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
myinotify = {path = "../myinotify"}
libc = "0.2"